version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: iotMan_postgres_container
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: iotMan_api
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      - DB_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: uvicorn main:app --host 0.0.0.0 --port 80 --workers 3

volumes:
  db-data:
